### ISSUE TITLE
1.4.0 Todo

### ISSUE THREAD

**Issue by DHolloran** [DHolloran/wp-better-attachments#54]
- [ ] Meta box styling (responsive).
- [x] Add actions at the top and bottom of the meta box.
- [x] Finish add attachments.
- [x] Add attachments to multiple posts.
- [ ] Add attachments to multiple posts settings/filters.
- [ ] Settings page.
- [ ] Media library links Unattach/Reattach.
- [ ] Media library links Unattach/Reattach settings/filters.
- [ ] Edit modal (possibly use 3.9 editing capabilities).
- [ ] Image crop rebuild.
- [ ] Image crop rebuild settings/filters.
- [x] Add a way to send notifications
- [ ] Add better documentation
- [ ] Settings migration tool
- [ ] Add uninstall clean up
- [ ] Add notification check either using `wp_schedule_event();`
- [ ] Add ability to filter media modal button

Optional
- [ ] Filter the meta box by type.
- [ ] Add custom fields to media page.
- [ ] Add custom fields to media page settings/filters.
- [ ] Add external attachments
- [ ] Add external attachments settings/filters.
- [ ] Add multiple meta boxes.
- [ ] Add multiple meta boxes settings/filters.
